### ISSUE TITLE
M1 Mac errors, please advise.

### ISSUE THREAD

**Issue by jamesxsc** [pfroud/JVisa#6]
I'm looking to use this on M1 mac. I have NI-VISA installed but I get the following trace.
```bash
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'visa':
dlopen(libvisa.dylib, 0x0009): tried: '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/./libvisa.dylib' (no such file), '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/../lib/libvisa.dylib' (no such file), 'libvisa.dylib' (no such file), '/usr/lib/libvisa.dylib' (no such file), '/Users/jconway@endomag.com/IdeaProjects/VISAread/libvisa.dylib' (no such file)
dlopen(libvisa.dylib, 0x0009): tried: '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/./libvisa.dylib' (no such file), '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/../lib/libvisa.dylib' (no such file), 'libvisa.dylib' (no such file), '/usr/lib/libvisa.dylib' (no such file), '/Users/jconway@endomag.com/IdeaProjects/VISAread/libvisa.dylib' (no such file)
dlopen(/Library/Frameworks/visa.framework/visa, 0x0009): tried: '/Library/Frameworks/visa.framework/visa' (fat file, but missing compatible architecture (have (x86_64), need (arm64e))), '/System/Library/Frameworks/visa.framework/visa' (no such file), '/Library/Frameworks/VISA.framework/Versions/A/VISA' (fat file, but missing compatible architecture (have (x86_64), need (arm64e))), '/System/Library/Frameworks/VISA.framework/Versions/A/VISA' (no such file)
Native library (darwin-aarch64/libvisa.dylib) not found in resource path (/Users/jconway@endomag.com/IdeaProjects/VISAread/out/production/VISAread:/Users/jconway@endomag.com/Downloads/jSSC-2.8.0-Release/jssc.jar:/Users/jconway@endomag.com/Downloads/JVisa-1.0-with-dependencies.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.Native.load(Native.java:596)
	at xyz.froud.jvisa.JVisaResourceManager.<init>(JVisaResourceManager.java:126)
	at VISARead.<init>(VISARead.java:28)
	at VISARead.main(VISARead.java:42)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libvisa.dylib, 0x0009): tried: '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/./libvisa.dylib' (no such file), '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/../lib/libvisa.dylib' (no such file), 'libvisa.dylib' (no such file), '/usr/lib/libvisa.dylib' (no such file), '/Users/jconway@endomag.com/IdeaProjects/VISAread/libvisa.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libvisa.dylib, 0x0009): tried: '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/./libvisa.dylib' (no such file), '/Users/jconway@endomag.com/Library/Java/JavaVirtualMachines/temurin-17.0.4.1/Contents/Home/bin/../lib/libvisa.dylib' (no such file), 'libvisa.dylib' (no such file), '/usr/lib/libvisa.dylib' (no such file), '/Users/jconway@endomag.com/IdeaProjects/VISAread/libvisa.dylib' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/visa.framework/visa, 0x0009): tried: '/Library/Frameworks/visa.framework/visa' (fat file, but missing compatible architecture (have (x86_64), need (arm64e))), '/System/Library/Frameworks/visa.framework/visa' (no such file), '/Library/Frameworks/VISA.framework/Versions/A/VISA' (fat file, but missing compatible architecture (have (x86_64), need (arm64e))), '/System/Library/Frameworks/VISA.framework/Versions/A/VISA' (no such file)
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 7 more
	Suppressed: java.io.IOException: Native library (darwin-aarch64/libvisa.dylib) not found in resource path (/Users/jconway@endomag.com/IdeaProjects/VISAread/out/production/VISAread:/Users/jconway@endomag.com/Downloads/jSSC-2.8.0-Release/jssc.jar:/Users/jconway@endomag.com/Downloads/JVisa-1.0-with-dependencies.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 7 more

Process finished with exit code 1
```
Thanks

**Comment by pfroud** [comment]
This message
```
fat file, but missing compatible architecture (have (x86_64), need (arm64e))
```
indicates that 
* The Java Virtual Machine is running with `arm64e` architecture. (The Apple M1 is ARM-based.)
* The only VISA native library files found have `x86-64` architecture. (The Intel processors in previous Macs used that architecture.) 

The architecture of the JVM must match the architecture of the native library file. 

So the options are:
* Install a Java Virtual Machine with `x86-64` architecture. That architecture may also be called something like `x64` or `amd64`. 
* Install a version of NI-VISA which runs natively on Apple Silicon - I don't think NI has made that yet.

**Comment by jamesxsc** [comment]
Hi Peter, I will try this. Thanks

**Comment by jamesxsc** [comment]
Understandably, I haven't had any success installing an x64 JVM on my M1. NI-VISA itself runs fine on Apple Silicon. Perhaps they just haven't made a library for external use? Or is it called something else?

**Comment by pfroud** [comment]
How are you installing JVMs? (Command-line?) 

I looks like you can download an x64 Temurin for macOS here: https://adoptium.net/temurin/releases
